#!/bin/bash
set -e
BASEDIR=$(dirname $0)
source $BASEDIR/inc_msg.sh
source $BASEDIR/inc_dependencies.sh
HOSTS=/etc/hosts
HOSTS_STATIC=${HOSTS}.static
AD_AWAY_HOSTS_URL=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

set_dependencies "curl"
check_dependencies

function create_static_hosts(){
    echo "# Private hosts entries"
    echo ""
    cat $HOSTS
    echo ""
    echo "# AdAway Host Entries"
    echo ""
}

function pull_ad_away_hosts(){
    cat ${HOSTS_STATIC} > ${HOSTS}
    # only trust empty lines, comments and dns entries that start with 0.0.0.0 for security reasons
    curl -s ${AD_AWAY_HOSTS_URL} | grep "^0\.0\.0\.0\|^#\|^$" >> ${HOSTS}
}

[ -f ${HOSTS_STATIC} ] || create_static_hosts > ${HOSTS_STATIC} || abort "Could not create static hosts file!"
pull_ad_away_hosts
