#!/bin/bash
set -e
BASEDIR=$(dirname $0)
source $BASEDIR/inc_dependencies.sh
set_dependencies fc-cache
function print_usage(){
    cat << EOF
Usage: $(basename $0) <font.ttf>"

EOF
	print_dependencies
}
if [ "x$1" == "x-h" ] || [ "x$1" == "x--help" ];then
    print_usage
    exit 0
fi

check_dependencies

FONT_FILE=$1
[ -z "$FONT_FILE" ] && abort "Argument missing!"
[ -f "$FONT_FILE" ] || abort "File not found: $FONT_FILE"

FONTSDIR=$HOME/.local/share/fonts
mkdir -p $FONTSDIR
cp $FONT_FILE $FONTSDIR
fc-cache
