#!/bin/bash
set -e
BASEDIR=$(dirname $0)
source $BASEDIR/inc_dependencies.sh
source $BASEDIR/inc_msg.sh

set_dependencies openssl

function print_usage(){
    cat << EOF
Usage: $(basename $0) <DOMAIN>

EOF
print_dependencies
}
if [ "x$1" == "x-h" ] || [ "x$1" == "x--help" ];then
    print_usage
    exit 0
fi

DOMAIN=$1
[ -z "$DOMAIN" ] && abort "Argument <DOMAIN> missing!"

check_dependencies

openssl s_client -connect $DOMAIN:443 \
    -servername $DOMAIN </dev/null 2>/dev/null |\
    openssl x509 -in /dev/stdin -noout -dates |\
	grep notAfter |\
	cut -d'=' -f 2
