#!/bin/bash
set -e
BASEDIR=$(dirname $0)
source $BASEDIR/inc_msg.sh
function print_usage {
    printf "Usage: $(basename $0) <dev|target_dir>\n";
}

if [ "x$1" == "x-h" ] || [ "x$1" == "x--help" ]; then
    printf "Creates a tempdir and chroots into it.\n\n"
    print_usage
    exit 0
fi
TARGET_DEV=$1
[ -z "${TARGET_DEV}" ] && abort $(print_usage)
if [ -d "${TARGET_DEV}" ]; then
    TARGET="${TARGET_DEV}"
else
    TARGET=$(mktemp -d)
    mount ${TARGET_DEV} ${TARGET}
fi
for DIR in \
    "/dev" \
    "/dev/pts" \
    "/proc" \
    "/sys" 
do
    [ -d ${TARGET}${DIR} ] || mkdir -p ${TARGET}${DIR}
    mount --bind ${DIR} ${TARGET}${DIR}
done
read -p "Copy resolv.conf to target system? [y/N]" CPRC
if [ "x${CPRC}" == "xy" ];then
    cp /etc/resolv.conf $TARGET/etc/resolv.conf
fi
chroot $TARGET /bin/bash
sleep 1
for DIR in \
    "/dev/pts" \
    "/dev" \
    "/proc" \
    "/sys" 
do
    umount ${TARGET}${DIR}
    rmdir  ${TARGET}${DIR}
done
umount $TARGET
rmdir $TARGET
