#!/bin/bash
set -e
BASEDIR=$(dirname $0)
SOURCES_LIST=/etc/apt/sources.list
DEBIAN_RELEASE_NAME=$(grep ^VERSION= /etc/os-release | sed -e "s/.*(\(.*\)).*/\1/")
source $BASEDIR/inc_msg.sh
source $BASEDIR/inc_dependencies.sh
set_dependencies "aptitude"
function print_usage(){
    cat << EOF
Usage: 
    $(basename $0) [ packages .... ]"
    
    Adds a backports entry to $SOURCES_LIST (if it is not already present)
    Installs packages given as arguments from backports repo 

or:
    $(basename $0) -l | --list
    
    Lists installed backports packages

or:
    $(basename $0) -h | --help
    
    Prints this help

EOF
print_dependencies
}
if [ "x$1" == "x-h" ] || [ "x$1" == "x--help" ];then
    print_usage
    exit 0
elif [ "x$1" == "x-l" ] || [ "x$1" == "x--list" ];then
    check_dependencies
    aptitude search '?narrow(?version(CURRENT),?origin(Debian Backports))' -F '%100p'
    exit 0
else
    check_dependencies
fi


[ "$(id -u)" == "0" ] || abort "Run as root!"

function setup_bpo(){
    read -p "Did not find backports entry in ${SOURCES_LIST}. Add it now? [Y/n]: " _add
    [[ "${_add}" =~ [nN] ]] || \
        echo "" >> ${SOURCES_LIST} && \
        echo "# ${DEBIAN_RELEASE_NAME} backports" >> ${SOURCES_LIST} && \
        echo "deb http://ftp.debian.org/debian ${DEBIAN_RELEASE_NAME}-backports main contrib non-free" >> ${SOURCES_LIST} \
        && aptitude update
}

grep -q ${DEBIAN_RELEASE_NAME}-backports ${SOURCES_LIST} || setup_bpo
[ $# -eq 0 ] && exit 

aptitude -t ${DEBIAN_RELEASE_NAME}-backports install $@
