#!/bin/bash
set -euo pipefail
basedir="$(dirname $0)"
source "${basedir}/inc_dependencies.sh"
set_dependencies fzf
function print_usage(){
    cat << EOF
Usage: $(basename $0) [OPTIONS] src_dir dst_dir

Options:
    --:
        Stop processing any further options

    -d,--debug:
        Run script in debugging mode

    -h,--help:
        Print this help
EOF
    print_dependencies
}
function abort(){
    echo "Error: $@" >&2
    exit 1
}

[ $# -eq 0 ] && abort "Arguments missing"

check_dependencies

if [ "${1}" == "-h" ] || [ "${1}" == "--help" ];then
    print_usage
    exit 0
fi
no_opts="n"
args=()
while [ $# -gt 0 ];do
    if [ "${no_opts}" == "y" ] && [[ "${1}" =~ \-.* ]];then
        args+="${1} "
    else
        case ${1} in
            '--')
                no_opts="y"
                ;;
            '-d'|'--debug')
                set -xe
                ;;
            '-h'|'--help')
                print_usage
                exit 0
                ;;
            *)
                args+=("${1}")
                ;;
        esac
    fi
    shift
done


[ ${#args[@]} -lt 2 ] && abort "Arguments missing"

src="${args[0]}"
dst="${args[1]}"
cmd="mv -v"
[ "$(basename "$0")" == "icp" ] && cmd="cp -vr"
default_ifs=$IFS
IFS=$'\n';
for f in $(ls -1rv "${src}" | fzf -m); do
    IFS=$default_ifs
    ${cmd} "${src}/${f}" "${dst}/"
    IFS=$'\n';
done
