#!/bin/bash
set -e
BASEDIR=$(dirname $0)
source $BASEDIR/inc_dependencies.sh
source $BASEDIR/inc_msg.sh
function print_usage(){
    cat << EOF
Usage: $(basename $0) <video-file>"
EOF
}
if [ "x$1" == "x-h" ] || [ "x$1" == "x--help" ];then
    print_usage
    exit 0
fi
VID=$1
[ -z "$VID" ] && abort "Missing argument <video-file>"
[ ! -f "$VID" ] && abort "$VID: File not found"

set_dependencies melt
check_dependencies

melt framebuffer:$VID reverse=1 -consumer xml:reverse.mlt

