#!/bin/bash
set -e
BASEDIR=$(dirname $0)
source $BASEDIR/inc_msg.sh
function print_usage(){
    cat << EOF
Usage: $(basename $0)" <args>

Disables the screensaver while executing <args>
EOF
}
if [ -z "$1" ] || [ "x$1" == "x-h" ] || [ "x$1" == "x--help" ];then
    print_usage
    exit 0
fi
xset -dpms
xset s off
eval "$@"
xset +dpms
xset s on
