#!/bin/bash
set -e
for PACNEW_FILE in $(locate .pacnew | grep "\.pacnew$"); do
    echo ""
    read -p "Handle $PACNEW_FILE? [Yn] " HANDLE
    if [[ "$HANDLE" =~ [Nn] ]];then
       continue
    fi
    ORIG_FILE=${PACNEW_FILE/\.pacnew/}
    diff $ORIG_FILE $PACNEW_FILE || true
    echo ""
    echo "What do you want to do?"
    select MY_RESULT in {"delete .pacnew","override current","merge","ignore"}; do
        [ -z "$MY_RESULT" ] || break
        echo ""
        echo "Invalid choice"
    done
    case $MY_RESULT in
        'delete .pacnew')
            rm -fv $PACNEW_FILE
            ;;
        'override current')
            mv -fv $PACNEW_FILE $ORIG_FILE
            ;;
        'merge')
            vimdiff $ORIG_FILE $PACNEW_FILE
            echo ""
            read -p "Remove $PACNEW_FILE? [Yn] " REMOVE
            [[ "$REMOVE" =~ [Nn] ]] || rm -fv $PACNEW_FILE
            ;;
        'ignore')
            ;;
    esac

done
