#!/bin/bash
set -e
for PACNEW_FILE in $(locate .pacnew | grep "\.pacnew$"); do
    read -p "Handle $PACNEW_FILE? [Yn] " handle
    if [[ "$handle" =~ [Nn] ]];then
       continue
    fi
    ORIG_FILE=${PACNEW_FILE/\.pacnew/}
    diff $ORIG_FILE $PACNEW_FILE || true
    echo ""
    echo "What do you want to do?"
    select MY_RESULT in {"delete .pacnew","override current","merge"}; do
        [ -z "$MY_RESULT" ] || break
        echo ""
        echo "Invalid choice"
    done
    case $MY_RESULT in
        'delete .pacnew')
            echo "Deleting .pacnew file"
            rm -f $PACNEW_FILE
            ;;
        'override current')
            echo "Overwriting current file with .pacnew file"
            mv -f $PACNEW_FILE $ORIG_FILE
            ;;
        'merge')
            echo "Open mergetool"
            vimdiff $ORIG_FILE $PACNEW_FILE
            ;;
    esac

done
