#!/bin/bash
BASEDIR=$(dirname $0)
source $BASEDIR/inc_msg.sh
source $BASEDIR/inc_dependencies.sh
function print_usage(){
    echo "Usage: $(basename $0) <socket-file>"
    print_dependencies
}

function assign_file () {
	if [ "x$SOCKET_FILE" == "x" ];then
		SOCKET_FILE=$1
	else
		abort "No more than one socket file allowed"
	fi
}

set_dependencies "socat"

NO_OPTS="n"
SOCKET_FILE=""
RAW="n"
while [ $# -gt 0 ];do
    if [ "x$NO_OPTS" == "xy" ] && [[ "$1" =~ \-.* ]];then
        assign_file $1
    else
        case $1 in
            '--')
                NO_OPTS="y"
                ;;
            '-h'|'--help')
                print_usage
                exit 0
                ;;
            '-r'|'--raw')
                RAW="y"
                ;;
            *)
                assign_file $1
                ;;
        esac
    fi
    shift
done

check_dependencies

[ -z "$SOCKET_FILE" ] && abort "Socket file argument missing!"
[ -e "$SOCKET_FILE" ] || abort "$SOCKET_FILE: File not found"

function negotiate_qmp_capabilities () {
    echo '{ "execute": "qmp_capabilities" }'
}

function pre_process () {
    local input=$(echo "$@")
	if [ "x$RAW" == "xy" ];then
		local output=$input
	else 
		local output=$(echo $input | sed -e 's/\(.*\)/{ "execute": "human-monitor-command", "arguments": { "command-line": "\1" } }/g' )
	fi
	echo $output
}

function qmp_shell () {
	negotiate_qmp_capabilities
	while [ "x$CMD" != "xbye" ] && [ -e "$SOCKET_FILE" ]; do
		read CMD
		[ -n "$CMD" ] && pre_process "$CMD" 	
        [ "x$CMD" == "xquit" ] && break
	done 
}

qmp_shell | socat - UNIX-CONNECT:$SOCKET_FILE
