#!/bin/bash
function print_usage(){
    echo "Usage: $(basename $0) <header>"
}
if [ "x$1" == "x-h" ]; then
    printf "Tries to find the specified header file on your system and pipes it to the pager defined in \$PAGER or less if \$PAGER is empty.\n\n"
    print_usage
    exit 0
fi
BASEDIR=$(dirname $0)
source $BASEDIR/inc_msg.sh
HEADER=$1
[ -z $HEADER ] && abort $(print_usage)
[[ "$HEADER" =~ .*\.h$ ]] || HEADER="${HEADER}.h"
for PREFIX in \
    "" \
    "sys/" \
    "bits/" \
    "asm/" \
    "linux/" 
do
    for LOCATION in \
        "/usr/include" \
        "/usr/include/mysql" \
        "/usr/local/include" \
        "."
    do
        [ -f ${LOCATION}/${PREFIX}${HEADER} ] && exec ${PAGER:-less} ${LOCATION}/${PREFIX}${HEADER};
    done
done

abort "Header $HEADER not found!"
