#!/bin/bash
function print_usage(){
    echo "Usage: $(basename $0) [header]"
}
if [ "x$1" == "x-h" ]; then
    echo "$(basename $0) tries to find the specified header file on your system and pipes it to the pager defined in \$PAGER or less if \$PAGER is empty."
    echo ""
    print_usage
    exit 0
fi
BASEDIR=$(dirname $0)
source $BASEDIR/inc_msg.sh
HEADER=$1
[ -z $HEADER ] && abort $(print_usage)
for LOCATION in \
    /usr/include/ \
    /usr/local/include/ \
    .
do
    [ -f $LOCATION/$HEADER ] && exec ${PAGER:-less} $LOCATION/$HEADER;
done
abort "Header $HEADER not found!"
