#!/bin/bash
BASEDIR=$(dirname $0)
source $BASEDIR/inc_msg.sh
source $BASEDIR/inc_dependencies.sh
function print_usage(){
    echo "Usage: $(basename $0) <initrd-file> [<compression-type>]"
    echo "where compression-type is one of xz|gz|zip|bz2 and gz is the default"
}

if [ "x$1" == "x-h" ];then
    print_usage
    exit 0
fi

[ "$(id -u)" == "0" ] || abort "Need root privileges for cpio to be happy!"


INITRD=$1
[ -z "$INITRD" ] && abort "Initrd file argument missing"
[ -f "$INITRD" ] || abort "Initrd file $INITRD not found!"

COMPRESSION_TYPE=${2:-gz}
case $COMPRESSION_TYPE in 
    'gz')
        UNPACK_CMD="gunzip"
        UNPACK_FLAGS=""
        ;;
    'zip')
        UNPACK_CMD="unzip"
        UNPACK_FLAGS=""
        ;;
    'xz')
        UNPACK_CMD="xz"
        UNPACK_FLAGS="-d"
        ;;
    'bz2')
        UNPACK_CMD="bunzip2"
        UNPACK_FLAGS=""
        ;;
    *)
        abort "Invalid compression type $COMPRESSION_TYPE"
        ;;
esac

set_dependencies $UNPACK_CMD cpio
check_dependencies

set -e
TARGET_DIR=$(mktemp -d)
CONTENT_DIR=${TARGET_DIR}/initrd_content
cp "$INITRD" $TARGET_DIR/initrd.${COMPRESSION_TYPE}
cd $TARGET_DIR
${UNPACK_CMD} ${UNPACK_FLAGS} "initrd.${COMPRESSION_TYPE}" 
mkdir -p $CONTENT_DIR
cd $CONTENT_DIR
cpio -id < "${TARGET_DIR}/initrd"
echo "initramfs content unpacked to $CONTENT_DIR"
