#!/bin/bash
set -e
BASEDIR=$(dirname $0)
source $BASEDIR/inc_msg.sh
function print_usage(){
    cat << EOF
Usage: $(basename $0) <dir>
EOF
}
if [ "x$1" == "x-h" ] || [ "x$1" == "x--help" ];then
    print_usage
    exit 0
fi
DIR=$1
[ -z "${DIR}" ] && abort "Arguments missing!"
cd "${DIR}"
find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;
