complete -f -W \
    "add \
    check \
    check-all \
    edit \
    remove \
    restore \
    sync \
    sync-all \
    untrack \
    --abort-on-conflict \
    --backup-on-conflict \
    --debug \
    --help \
    --ignore-on-conflict \
    --restore-on-conflict \
    --suppress-synced \
    --untrack-on-conflict \
    " cti
